import "dotenv/config";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/**
 * Versioned source-of-truth tool for the three Cloudflare cache rules
 * (http_request_cache_settings phase). Replaces the untracked tmp_ui/cf-rule-patch.py
 * read-patch-PUT throwaway with a committed snapshot + diff + apply flow.
 *
 *   node scripts/cf-ruleset.mjs pull    GET the live ruleset -> infra/cf-cache-ruleset.json
 *   node scripts/cf-ruleset.mjs diff    GET live, diff against the committed file (exit 1 on drift)
 *   node scripts/cf-ruleset.mjs apply --yes   PUT the committed file's rules to the zone
 *
 * Token scope (least privilege): ruleset read/edit is an OPERATOR capability used a couple of
 * times a year, so it is kept OUT of the always-on container. This tool reads
 * CF_RULESET_API_TOKEN (a separate operator token with Zone:Cache Rules / ruleset edit). It
 * falls back to CF_API_TOKEN for a transition period but warns — once CF_API_TOKEN is re-scoped
 * to Zone:Cache Purge:Edit only (its sole runtime need), set CF_RULESET_API_TOKEN in your shell
 * to maintain the rules. Do NOT put CF_RULESET_API_TOKEN in .env / the compose env_file, or the
 * elevated scope lands back in the 24/7 container.
 */

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const RULESET_FILE = path.join(root, "infra", "cf-cache-ruleset.json");
const PHASE_PATH = "rulesets/phases/http_request_cache_settings/entrypoint";

// The writable fields CF accepts on a rule when PUTting the ruleset. Volatile metadata
// (id, version, ref, last_updated) is regenerated by CF and excluded from diff/apply.
const RULE_FIELDS = ["description", "expression", "action", "action_parameters", "enabled"];

function fail(message, code = 1) {
  console.error(message);
  process.exit(code);
}

function resolveAuth() {
  const zone = process.env.CF_ZONE_ID?.trim();
  if (!zone) fail("CF_ZONE_ID is required (set it in .env).", 2);
  const rulesetToken = process.env.CF_RULESET_API_TOKEN?.trim();
  const token = rulesetToken || process.env.CF_API_TOKEN?.trim();
  if (!token) fail("Set CF_RULESET_API_TOKEN (operator token with ruleset edit) to maintain cache rules.", 2);
  if (!rulesetToken) {
    console.warn(
      "[cf-ruleset] WARNING: falling back to CF_API_TOKEN. Re-scope CF_API_TOKEN to Zone:Cache Purge:Edit only and set CF_RULESET_API_TOKEN for ruleset ops (see docs/CLOUDFLARE.md)."
    );
  }
  return { zone, token };
}

function cfHeaders(token) {
  return { Authorization: `Bearer ${token}`, "Content-Type": "application/json" };
}

async function cfRequest(zone, token, method, body) {
  const url = `https://api.cloudflare.com/client/v4/zones/${zone}/${PHASE_PATH}`;
  const response = await fetch(url, { method, headers: cfHeaders(token), body: body ? JSON.stringify(body) : undefined });
  const text = await response.text().catch(() => "");
  let parsed;
  try {
    parsed = text ? JSON.parse(text) : {};
  } catch {
    parsed = {};
  }
  if (!response.ok || parsed.success === false) {
    const errors = Array.isArray(parsed.errors) ? parsed.errors.map((e) => `${e.code ?? ""} ${e.message ?? ""}`.trim()).join("; ") : "";
    fail(`Cloudflare ${method} failed (HTTP ${response.status}): ${errors || text.slice(0, 300)}`);
  }
  return parsed.result;
}

function normalizeRules(rules) {
  return (rules ?? []).map((rule) => {
    const out = {};
    for (const field of RULE_FIELDS) if (rule[field] !== undefined) out[field] = rule[field];
    return out;
  });
}

function readRulesetFile() {
  if (!fs.existsSync(RULESET_FILE)) fail(`Missing ${path.relative(root, RULESET_FILE)} — run: node scripts/cf-ruleset.mjs pull`, 2);
  return JSON.parse(fs.readFileSync(RULESET_FILE, "utf8"));
}

async function cmdPull() {
  const { zone, token } = resolveAuth();
  const result = await cfRequest(zone, token, "GET");
  fs.mkdirSync(path.dirname(RULESET_FILE), { recursive: true });
  fs.writeFileSync(RULESET_FILE, `${JSON.stringify(result, null, 2)}\n`);
  console.log(`pulled ${result.rules?.length ?? 0} rules -> ${path.relative(root, RULESET_FILE)}`);
  for (const rule of result.rules ?? []) console.log(`  - ${rule.description ?? "(no description)"}`);
}

async function cmdDiff() {
  const { zone, token } = resolveAuth();
  const live = normalizeRules((await cfRequest(zone, token, "GET")).rules);
  const file = normalizeRules(readRulesetFile().rules);
  const liveJson = JSON.stringify(live, null, 2);
  const fileJson = JSON.stringify(file, null, 2);
  if (liveJson === fileJson) {
    console.log("in sync: committed ruleset matches the live zone.");
    return;
  }
  console.error("DRIFT: committed infra/cf-cache-ruleset.json differs from the live zone.");
  console.error(`  live rules:      ${live.length} [${live.map((r) => r.description?.split(" — ")[0]).join(", ")}]`);
  console.error(`  committed rules: ${file.length} [${file.map((r) => r.description?.split(" — ")[0]).join(", ")}]`);
  console.error("Run `node scripts/cf-ruleset.mjs pull` to adopt live, or `apply --yes` to push the committed file.");
  process.exit(1);
}

async function cmdApply(args) {
  const file = readRulesetFile();
  if (file._unverified_reconstruction) {
    fail(
      "Refusing to apply: infra/cf-cache-ruleset.json is the hand-reconstructed seed, not a live snapshot.\n" +
        "Run `node scripts/cf-ruleset.mjs pull` on a host with CF creds first to capture the authoritative ruleset, verify it, then apply.",
      2
    );
  }
  const rules = normalizeRules(file.rules);
  if (rules.length === 0) fail("Committed ruleset has no rules; refusing to PUT an empty ruleset.", 2);
  if (!args.includes("--yes")) {
    console.log(`DRY RUN — would PUT ${rules.length} rules (replaces the whole http_request_cache_settings ruleset):`);
    for (const rule of rules) console.log(`  - ${rule.description ?? "(no description)"}`);
    console.log("Re-run with --yes to apply.");
    return;
  }
  const { zone, token } = resolveAuth();
  const result = await cfRequest(zone, token, "PUT", { rules });
  console.log(`applied ${result.rules?.length ?? 0} rules to zone ${zone}.`);
}

const command = process.argv[2];
const rest = process.argv.slice(3);
switch (command) {
  case "pull":
    await cmdPull();
    break;
  case "diff":
    await cmdDiff();
    break;
  case "apply":
    await cmdApply(rest);
    break;
  default:
    fail("Usage: node scripts/cf-ruleset.mjs <pull|diff|apply [--yes]>", 2);
}
